/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbschlussRouteImport } from './routes/abschluss'
import { Route as ArtikelRouteImport } from './routes/artikel'
import { Route as BerichteRouteImport } from './routes/berichte'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as InventarRouteImport } from './routes/inventar'
import { Route as KuecheRouteImport } from './routes/kueche'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as ReservierungenRouteImport } from './routes/reservierungen'
import { Route as SchnellkasseRouteImport } from './routes/schnellkasse'
import { Route as TischTableIdRouteImport } from './routes/tisch.$tableId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbschlussRoute = AbschlussRouteImport.update({
  id: '/abschluss',
  path: '/abschluss',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRoute = ArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const BerichteRoute = BerichteRouteImport.update({
  id: '/berichte',
  path: '/berichte',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarRoute = InventarRouteImport.update({
  id: '/inventar',
  path: '/inventar',
  getParentRoute: () => rootRouteImport,
} as any)
const KuecheRoute = KuecheRouteImport.update({
  id: '/kueche',
  path: '/kueche',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservierungenRoute = ReservierungenRouteImport.update({
  id: '/reservierungen',
  path: '/reservierungen',
  getParentRoute: () => rootRouteImport,
} as any)
const SchnellkasseRoute = SchnellkasseRouteImport.update({
  id: '/schnellkasse',
  path: '/schnellkasse',
  getParentRoute: () => rootRouteImport,
} as any)
const TischTableIdRoute = TischTableIdRouteImport.update({
  id: '/tisch/$tableId',
  path: '/tisch/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abschluss': typeof AbschlussRoute
  '/artikel': typeof ArtikelRoute
  '/berichte': typeof BerichteRoute
  '/einstellungen': typeof EinstellungenRoute
  '/inventar': typeof InventarRoute
  '/kueche': typeof KuecheRoute
  '/personal': typeof PersonalRoute
  '/reservierungen': typeof ReservierungenRoute
  '/schnellkasse': typeof SchnellkasseRoute
  '/tisch/$tableId': typeof TischTableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abschluss': typeof AbschlussRoute
  '/artikel': typeof ArtikelRoute
  '/berichte': typeof BerichteRoute
  '/einstellungen': typeof EinstellungenRoute
  '/inventar': typeof InventarRoute
  '/kueche': typeof KuecheRoute
  '/personal': typeof PersonalRoute
  '/reservierungen': typeof ReservierungenRoute
  '/schnellkasse': typeof SchnellkasseRoute
  '/tisch/$tableId': typeof TischTableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abschluss': typeof AbschlussRoute
  '/artikel': typeof ArtikelRoute
  '/berichte': typeof BerichteRoute
  '/einstellungen': typeof EinstellungenRoute
  '/inventar': typeof InventarRoute
  '/kueche': typeof KuecheRoute
  '/personal': typeof PersonalRoute
  '/reservierungen': typeof ReservierungenRoute
  '/schnellkasse': typeof SchnellkasseRoute
  '/tisch/$tableId': typeof TischTableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abschluss'
    | '/artikel'
    | '/berichte'
    | '/einstellungen'
    | '/inventar'
    | '/kueche'
    | '/personal'
    | '/reservierungen'
    | '/schnellkasse'
    | '/tisch/$tableId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abschluss'
    | '/artikel'
    | '/berichte'
    | '/einstellungen'
    | '/inventar'
    | '/kueche'
    | '/personal'
    | '/reservierungen'
    | '/schnellkasse'
    | '/tisch/$tableId'
  id:
    | '__root__'
    | '/'
    | '/abschluss'
    | '/artikel'
    | '/berichte'
    | '/einstellungen'
    | '/inventar'
    | '/kueche'
    | '/personal'
    | '/reservierungen'
    | '/schnellkasse'
    | '/tisch/$tableId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbschlussRoute: typeof AbschlussRoute
  ArtikelRoute: typeof ArtikelRoute
  BerichteRoute: typeof BerichteRoute
  EinstellungenRoute: typeof EinstellungenRoute
  InventarRoute: typeof InventarRoute
  KuecheRoute: typeof KuecheRoute
  PersonalRoute: typeof PersonalRoute
  ReservierungenRoute: typeof ReservierungenRoute
  SchnellkasseRoute: typeof SchnellkasseRoute
  TischTableIdRoute: typeof TischTableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abschluss': {
      id: '/abschluss'
      path: '/abschluss'
      fullPath: '/abschluss'
      preLoaderRoute: typeof AbschlussRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berichte': {
      id: '/berichte'
      path: '/berichte'
      fullPath: '/berichte'
      preLoaderRoute: typeof BerichteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventar': {
      id: '/inventar'
      path: '/inventar'
      fullPath: '/inventar'
      preLoaderRoute: typeof InventarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kueche': {
      id: '/kueche'
      path: '/kueche'
      fullPath: '/kueche'
      preLoaderRoute: typeof KuecheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservierungen': {
      id: '/reservierungen'
      path: '/reservierungen'
      fullPath: '/reservierungen'
      preLoaderRoute: typeof ReservierungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schnellkasse': {
      id: '/schnellkasse'
      path: '/schnellkasse'
      fullPath: '/schnellkasse'
      preLoaderRoute: typeof SchnellkasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tisch/$tableId': {
      id: '/tisch/$tableId'
      path: '/tisch/$tableId'
      fullPath: '/tisch/$tableId'
      preLoaderRoute: typeof TischTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbschlussRoute: AbschlussRoute,
  ArtikelRoute: ArtikelRoute,
  BerichteRoute: BerichteRoute,
  EinstellungenRoute: EinstellungenRoute,
  InventarRoute: InventarRoute,
  KuecheRoute: KuecheRoute,
  PersonalRoute: PersonalRoute,
  ReservierungenRoute: ReservierungenRoute,
  SchnellkasseRoute: SchnellkasseRoute,
  TischTableIdRoute: TischTableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
